version: "3.1"

services:

  mysql:
    # image: mysql:5.7
    build: ./mysql # for import database dump
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql

  wordpress:
    image: wordpress
    domainname: ${SITE_DOMAINNAME}
    hostname: www
    links:
      - mysql
    environment:
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html:rw
