web:
  image: wordpress
  links:
    - mysql
  domainname: artsatlasgeelong.dev
  environment:
    WORDPRESS_DB_PASSWORD: password
    DOMAIN_NAME: "artsatlasgeelong.dev, www.artsatlasgeelong.dev"
  ports:
    - 80:80
  volumes:
    - ./app:/var/www/html:rw

mysql:
  build: mysql
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: wpdb
  volumes:
    - ./database:/var/lib/mysql