version: "3.2"

services:
  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    restart: "always"
    ports:
      - 53:53/tcp
      - 53:53/udp
    cap_add: 
      - NET_ADMIN
    # command: -A /dev/127.0.0.1 --log-facility=-
    volumes:
      - ./bin/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      - reverse-proxy

  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    restart: "always"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - reverse-proxy

  # letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   restart: always
  #   volumes_from:
  #     - nginx-proxy
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro     
  #     - ~/certs:/etc/nginx/certs:rw
  #   networks:
  #     - reverse-proxy

networks:
  reverse-proxy:
    external:
      name: reverse-proxy